# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutWindow(object):
    def setupUi(self, AboutWindow):
        AboutWindow.setObjectName("AboutWindow")
        AboutWindow.resize(462, 210)
        self.centralwidget = QtWidgets.QWidget(AboutWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(370, 150, 81, 51))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(33, 19, 381, 111))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 150, 51, 51))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 160, 251, 21))
        self.label_3.setObjectName("label_3")
        AboutWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AboutWindow)
        QtCore.QMetaObject.connectSlotsByName(AboutWindow)

    def retranslateUi(self, AboutWindow):
        _translate = QtCore.QCoreApplication.translate
        AboutWindow.setWindowTitle(_translate("AboutWindow", "关于作者"))
        self.pushButton.setText(_translate("AboutWindow", "确定"))
        self.label.setText(_translate("AboutWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:700;\">Copyright(c) 2025 rmxlinux</span></p><p align=\"center\"><span style=\" font-size:10pt; color:#0000ff;\">bug反馈请发邮箱：</span><a href=\"dandinking@buaa.edu.cn\"><span style=\" text-decoration: underline; color:#0000ff;\">dandinking@buaa.edu.cn</span></a></p><p align=\"center\"><span style=\" font-size:10pt;\">暂时无法将源码上传至github，敬请谅解。</span></p><p align=\"center\"><span style=\" font-size:10pt;\">您也可以关注我们的</span><a href=\"https://github.com/rmxlinux\"><span style=\" text-decoration: underline; color:#0000ff;\">github账号</span></a><span style=\" font-size:10pt;\">获取最新更新情报。</span></p></body></html>"))
        self.label_2.setText(_translate("AboutWindow", "TextLabel"))
        self.label_3.setText(_translate("AboutWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:700; font-style:italic; color:#e8000c;\">FrostLeaF小狐狸天下第一</span></p></body></html>"))
