# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Create_Window(object):
    def setupUi(self, Create_Window):
        Create_Window.setObjectName("Create_Window")
        Create_Window.resize(554, 488)
        self.centralwidget = QtWidgets.QWidget(Create_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 30, 341, 431))
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.button_new = QtWidgets.QPushButton(self.centralwidget)
        self.button_new.setGeometry(QtCore.QRect(380, 110, 71, 31))
        self.button_new.setObjectName("button_new")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(530, 110, 61, 31))
        self.label.setObjectName("label")
        self.button_finish = QtWidgets.QPushButton(self.centralwidget)
        self.button_finish.setGeometry(QtCore.QRect(380, 30, 131, 61))
        self.button_finish.setObjectName("button_finish")
        self.spin_new_count = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_new_count.setGeometry(QtCore.QRect(460, 110, 61, 31))
        self.spin_new_count.setMinimum(1)
        self.spin_new_count.setMaximum(19260817)
        self.spin_new_count.setObjectName("spin_new_count")
        self.button_delete = QtWidgets.QPushButton(self.centralwidget)
        self.button_delete.setGeometry(QtCore.QRect(380, 150, 71, 31))
        self.button_delete.setObjectName("button_delete")
        self.line_delete = QtWidgets.QLineEdit(self.centralwidget)
        self.line_delete.setGeometry(QtCore.QRect(480, 150, 41, 31))
        self.line_delete.setObjectName("line_delete")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(530, 150, 61, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(460, 150, 16, 31))
        self.label_3.setObjectName("label_3")
        self.console = QtWidgets.QTextEdit(self.centralwidget)
        self.console.setGeometry(QtCore.QRect(380, 190, 161, 211))
        self.console.setReadOnly(True)
        self.console.setObjectName("console")
        Create_Window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Create_Window)
        self.statusbar.setObjectName("statusbar")
        Create_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Create_Window)
        QtCore.QMetaObject.connectSlotsByName(Create_Window)

    def retranslateUi(self, Create_Window):
        _translate = QtCore.QCoreApplication.translate
        Create_Window.setWindowTitle(_translate("Create_Window", "谷图编辑器"))
        self.button_new.setText(_translate("Create_Window", "新建"))
        self.label.setText(_translate("Create_Window", "行"))
        self.button_finish.setText(_translate("Create_Window", "完成"))
        self.button_delete.setText(_translate("Create_Window", "删除"))
        self.line_delete.setText(_translate("Create_Window", "1"))
        self.label_2.setText(_translate("Create_Window", "行"))
        self.label_3.setText(_translate("Create_Window", "第"))
