# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(522, 222)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_Create = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Create.setGeometry(QtCore.QRect(310, 10, 201, 41))
        self.Button_Create.setObjectName("Button_Create")
        self.Button_Open = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Open.setEnabled(True)
        self.Button_Open.setGeometry(QtCore.QRect(310, 60, 201, 41))
        self.Button_Open.setCheckable(False)
        self.Button_Open.setDefault(False)
        self.Button_Open.setFlat(False)
        self.Button_Open.setObjectName("Button_Open")
        self.Button_Save = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Save.setEnabled(True)
        self.Button_Save.setGeometry(QtCore.QRect(310, 160, 201, 41))
        self.Button_Save.setObjectName("Button_Save")
        self.Button_Generate = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Generate.setGeometry(QtCore.QRect(310, 110, 201, 41))
        self.Button_Generate.setObjectName("Button_Generate")
        self.button_about = QtWidgets.QPushButton(self.centralwidget)
        self.button_about.setGeometry(QtCore.QRect(30, 150, 111, 41))
        self.button_about.setObjectName("button_about")
        self.button_help = QtWidgets.QPushButton(self.centralwidget)
        self.button_help.setGeometry(QtCore.QRect(160, 150, 111, 41))
        self.button_help.setObjectName("button_help")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 291, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "谷团余量示意图助手 2025.1.01beta"))
        self.Button_Create.setText(_translate("MainWindow", "新建"))
        self.Button_Open.setText(_translate("MainWindow", "打开"))
        self.Button_Save.setText(_translate("MainWindow", "保存到文件"))
        self.Button_Generate.setText(_translate("MainWindow", "生成图片"))
        self.button_about.setText(_translate("MainWindow", "关于我们"))
        self.button_help.setText(_translate("MainWindow", "帮助"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">谷团余量示意图助手 2025.1.01</span><span style=\" font-size:10pt; color:#aa00ff;\">beta</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:700;\">build on 2025/2/7 </span></p><p align=\"center\"><span style=\" font-size:10pt; color:#ff0000;\">此项目仍处于测试阶段。</span></p><p align=\"center\"><span style=\" font-size:10pt; color:#ff0000;\">部分功能可能无法正常工作。 </span></p></body></html>"))
