# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'match_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_match_window(object):
    def setupUi(self, match_window):
        match_window.setObjectName("match_window")
        match_window.resize(722, 556)
        self.centralwidget = QtWidgets.QWidget(match_window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 191, 21))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.scroll_options = QtWidgets.QScrollArea(self.centralwidget)
        self.scroll_options.setGeometry(QtCore.QRect(250, 20, 461, 521))
        self.scroll_options.setWidgetResizable(True)
        self.scroll_options.setObjectName("scroll_options")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 459, 519))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scroll_options.setWidget(self.scrollAreaWidgetContents)
        self.label_pic = QtWidgets.QLabel(self.centralwidget)
        self.label_pic.setGeometry(QtCore.QRect(20, 70, 201, 471))
        self.label_pic.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_pic.setWordWrap(True)
        self.label_pic.setObjectName("label_pic")
        match_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(match_window)
        QtCore.QMetaObject.connectSlotsByName(match_window)

    def retranslateUi(self, match_window):
        _translate = QtCore.QCoreApplication.translate
        match_window.setWindowTitle(_translate("match_window", "手动匹配"))
        self.label.setText(_translate("match_window", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:700; color:#0000ff;\">这个商品的图片是？</span></p></body></html>"))
        self.label_pic.setText(_translate("match_window", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:700;\">霜叶</span></p></body></html>"))
