# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mode_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mode_Window(object):
    def setupUi(self, Mode_Window):
        Mode_Window.setObjectName("Mode_Window")
        Mode_Window.setWindowModality(QtCore.Qt.WindowModal)
        Mode_Window.resize(321, 369)
        self.centralwidget = QtWidgets.QWidget(Mode_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.radio_folder = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_folder.setGeometry(QtCore.QRect(40, 30, 431, 31))
        self.radio_folder.setObjectName("radio_folder")
        self.radio_auto_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_auto_1.setEnabled(False)
        self.radio_auto_1.setGeometry(QtCore.QRect(40, 110, 431, 31))
        self.radio_auto_1.setObjectName("radio_auto_1")
        self.radio_auto_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_auto_2.setEnabled(False)
        self.radio_auto_2.setGeometry(QtCore.QRect(40, 190, 431, 31))
        self.radio_auto_2.setObjectName("radio_auto_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 310, 281, 51))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 140, 241, 41))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 220, 241, 91))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 60, 241, 41))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        Mode_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Mode_Window)
        QtCore.QMetaObject.connectSlotsByName(Mode_Window)

    def retranslateUi(self, Mode_Window):
        _translate = QtCore.QCoreApplication.translate
        Mode_Window.setWindowTitle(_translate("Mode_Window", "选择图片载入方式"))
        self.radio_folder.setText(_translate("Mode_Window", "从文件夹载入"))
        self.radio_auto_1.setText(_translate("Mode_Window", "从大图手动裁剪"))
        self.radio_auto_2.setText(_translate("Mode_Window", "从大图自动裁剪"))
        self.pushButton.setText(_translate("Mode_Window", "确定"))
        self.label.setText(_translate("Mode_Window", "<html><head/><body><p><span style=\" color:#ff0000;\">只需要给定商品大图，手动框选每个商品对应的区域，由电脑自动裁剪</span></p></body></html>"))
        self.label_2.setText(_translate("Mode_Window", "<html><head/><body><p><span style=\" color:#ff0000;\">只需要给定商品大图，点击各个商品的区域，电脑自动识别并裁剪</span></p><p><span style=\" font-weight:700; color:#ff0000;\">此功能可能会造成图片的严重拉伸。</span></p></body></html>"))
        self.label_3.setText(_translate("Mode_Window", "<html><head/><body><p><span style=\" color:#ff0000;\">需要一个图片文件夹，根据给定的商品名称匹配图片，如果有匹配不上的则手动匹配</span></p></body></html>"))
