# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Select_Window(object):
    def setupUi(self, Select_Window):
        Select_Window.setObjectName("Select_Window")
        Select_Window.resize(469, 227)
        self.centralwidget = QtWidgets.QWidget(Select_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.radio_folder = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_folder.setGeometry(QtCore.QRect(10, 10, 371, 31))
        self.radio_folder.setObjectName("radio_folder")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 40, 421, 31))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 170, 451, 51))
        self.pushButton.setObjectName("pushButton")
        self.radio_excel = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_excel.setGeometry(QtCore.QRect(10, 80, 431, 31))
        self.radio_excel.setObjectName("radio_excel")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 110, 421, 31))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        Select_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Select_Window)
        QtCore.QMetaObject.connectSlotsByName(Select_Window)

    def retranslateUi(self, Select_Window):
        _translate = QtCore.QCoreApplication.translate
        Select_Window.setWindowTitle(_translate("Select_Window", "请选择导入方式"))
        self.radio_folder.setText(_translate("Select_Window", "从图片文件夹导入"))
        self.label.setText(_translate("Select_Window", "<html><head/><body><p><span style=\" color:#ff0000;\">事先准备好图片文件夹，以图片文件名作为商品名，余量信息需自己填写。</span></p></body></html>"))
        self.pushButton.setText(_translate("Select_Window", "确定"))
        self.radio_excel.setText(_translate("Select_Window", "从Excel导入"))
        self.label_2.setText(_translate("Select_Window", "<html><head/><body><p><span style=\" color:#ff0000;\">导入Excel中的名称数据与余量数据，并选择图片文件夹。如果有找不到对应图片的商品，会手动进行绑定。</span></p></body></html>"))
