# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_view_window(object):
    def setupUi(self, view_window):
        view_window.setObjectName("view_window")
        view_window.resize(560, 327)
        self.centralwidget = QtWidgets.QWidget(view_window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 551, 301))
        self.label.setObjectName("label")
        view_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(view_window)
        self.statusbar.setObjectName("statusbar")
        view_window.setStatusBar(self.statusbar)

        self.retranslateUi(view_window)
        QtCore.QMetaObject.connectSlotsByName(view_window)

    def retranslateUi(self, view_window):
        _translate = QtCore.QCoreApplication.translate
        view_window.setWindowTitle(_translate("view_window", "预览"))
        self.label.setText(_translate("view_window", "TextLabel"))
